# Generated by Django 3.1.5 on 2021-01-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbs',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
