# Generated by Django 3.1.5 on 2021-01-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_climbs_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbs',
            name='address',
        ),
        migrations.AddField(
            model_name='climbs',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='climbs',
            name='rating',
            field=models.CharField(default='v0', max_length=5),
        ),
        migrations.AddField(
            model_name='climbs',
            name='state',
            field=models.CharField(default='TX', max_length=2),
        ),
    ]
