# Generated by Django 3.1.5 on 2021-01-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210126_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbs',
            name='comments',
            field=models.TextField(default='Add any notes/comments here.'),
        ),
    ]
