# Generated by Django 3.1.5 on 2021-01-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_climbs_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbs',
            name='comments',
            field=models.TextField(default=None),
        ),
    ]
