# Generated by Django 3.1.5 on 2021-01-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210127_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbs',
            name='typeOfClimb',
            field=models.CharField(choices=[('B', 'Boulder'), ('SC', 'Sport Climb')], default='B', max_length=2),
        ),
    ]
